name: Total Federation
run-name: ${{ github.actor }} runs it
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - id: 'auth'
        name: '1. Federate github workload identity'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/150418185326/locations/global/workloadIdentityPools/github/providers/totel-federation'
          service_account: 'github@germany-velen.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        with:
          install_components: gke-gcloud-auth-plugin
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: '2. Get Access Token'
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: '3. Setup kube context'
        run: gcloud container clusters get-credentials gcp-frankfurt --zone europe-west3-c --project germany-velen
      - name: "6. List GCP VM's"
        run: kubectl exec deploy/ubuntu  -c tools -n tools -- /bin/bash -c "/root/google-cloud-sdk/bin/gcloud compute instances list --project germany-velen | head"
      - name: "6. List AWS VM's"
        run: kubectl exec deploy/ubuntu  -c tools -n tools -- /bin/bash -c "/usr/local/bin/aws ec2 describe-instances | head"
      - name: "3-6. List Azure Resource Groups"
        run: kubectl exec deploy/ubuntu  -c tools -n tools -- /bin/bash -c "/usr/local/bin/az group list | head"

